import { Providers } from "./providers";
import { ClerkProvider } from '@clerk/nextjs'
//import './globals.css'
import type { Metadata } from 'next'
import { Atkinson_Hyperlegible } from 'next/font/google'
import Header from '@/components/ui/header'

const font = Atkinson_Hyperlegible({weight:"400", subsets: ['latin']})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
        <html lang="en">
          <head>
            <title>Ayup</title>
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <link rel="preload" href="/fonts/atkinson-regular.woff" as="font" type="font/woff" />
            <link rel="preload" href="/fonts/atkinson-bold.woff" as="font" type="font/woff" />
          </head>
          <body className="body">
              <ClerkProvider>
                  <link rel="stylesheet" type="text/css" href="/stylesheets/globals.css" />
                  <Providers>
                      <Header />
                      <main>

                              {children}
                      </main>
                  </Providers>
              </ClerkProvider>
          </body>
        </html>
  )
}
